package io.heapy.dimension

import ru.dimension.di.DimensionDI
import ru.dimension.di.ServiceLocator
import kotlin.jvm.java

fun main() {
    DimensionDI.builder()
        .scanPackages("io.heapy.dimension")
        .bind(Service::class.java, DefaultService::class.java)
        .bind(Service1::class.java, DefaultService1::class.java)
        .bind(Service2::class.java, DefaultService2::class.java)
        .bind(Service3::class.java, DefaultService3::class.java)
        .bind(Service4::class.java, DefaultService4::class.java)
        .bind(Service5::class.java, DefaultService5::class.java)
        .bind(Service6::class.java, DefaultService6::class.java)
        .bind(Service7::class.java, DefaultService7::class.java)
        .bind(Service8::class.java, DefaultService8::class.java)
        .bind(Service9::class.java, DefaultService9::class.java)
        .bind(Service10::class.java, DefaultService10::class.java)
        .bind(Service11::class.java, DefaultService11::class.java)
        .bind(Service12::class.java, DefaultService12::class.java)
        .bind(Service13::class.java, DefaultService13::class.java)
        .bind(Service14::class.java, DefaultService14::class.java)
        .bind(Service15::class.java, DefaultService15::class.java)
        .bind(Service16::class.java, DefaultService16::class.java)
        .bind(Service17::class.java, DefaultService17::class.java)
        .bind(Service18::class.java, DefaultService18::class.java)
        .bind(Service19::class.java, DefaultService19::class.java)
        .bind(Service20::class.java, DefaultService20::class.java)
        .bind(Service21::class.java, DefaultService21::class.java)
        .bind(Service22::class.java, DefaultService22::class.java)
        .bind(Service23::class.java, DefaultService23::class.java)
        .bind(Service24::class.java, DefaultService24::class.java)
        .bind(Service25::class.java, DefaultService25::class.java)
        .bind(Service26::class.java, DefaultService26::class.java)
        .bind(Service27::class.java, DefaultService27::class.java)
        .bind(Service28::class.java, DefaultService28::class.java)
        .bind(Service29::class.java, DefaultService29::class.java)
        .bind(Service30::class.java, DefaultService30::class.java)
        .bind(Service31::class.java, DefaultService31::class.java)
        .bind(Service32::class.java, DefaultService32::class.java)
        .bind(Service33::class.java, DefaultService33::class.java)
        .bind(Service34::class.java, DefaultService34::class.java)
        .bind(Service35::class.java, DefaultService35::class.java)
        .bind(Service36::class.java, DefaultService36::class.java)
        .bind(Service37::class.java, DefaultService37::class.java)
        .bind(Service38::class.java, DefaultService38::class.java)
        .bind(Service39::class.java, DefaultService39::class.java)
        .bind(Service40::class.java, DefaultService40::class.java)
        .bind(Service41::class.java, DefaultService41::class.java)
        .bind(Service42::class.java, DefaultService42::class.java)
        .bind(Service43::class.java, DefaultService43::class.java)
        .bind(Service44::class.java, DefaultService44::class.java)
        .bind(Service45::class.java, DefaultService45::class.java)
        .bind(Service46::class.java, DefaultService46::class.java)
        .bind(Service47::class.java, DefaultService47::class.java)
        .bind(Service48::class.java, DefaultService48::class.java)
        .bind(Service49::class.java, DefaultService49::class.java)
        .bind(Service50::class.java, DefaultService50::class.java)
        .bind(Service51::class.java, DefaultService51::class.java)
        .bind(Service52::class.java, DefaultService52::class.java)
        .bind(Service53::class.java, DefaultService53::class.java)
        .bind(Service54::class.java, DefaultService54::class.java)
        .bind(Service55::class.java, DefaultService55::class.java)
        .bind(Service56::class.java, DefaultService56::class.java)
        .bind(Service57::class.java, DefaultService57::class.java)
        .bind(Service58::class.java, DefaultService58::class.java)
        .bind(Service59::class.java, DefaultService59::class.java)
        .bind(Service60::class.java, DefaultService60::class.java)
        .bind(Service61::class.java, DefaultService61::class.java)
        .bind(Service62::class.java, DefaultService62::class.java)
        .bind(Service63::class.java, DefaultService63::class.java)
        .bind(Service64::class.java, DefaultService64::class.java)
        .bind(Service65::class.java, DefaultService65::class.java)
        .bind(Service66::class.java, DefaultService66::class.java)
        .bind(Service67::class.java, DefaultService67::class.java)
        .bind(Service68::class.java, DefaultService68::class.java)
        .bind(Service69::class.java, DefaultService69::class.java)
        .bind(Service70::class.java, DefaultService70::class.java)
        .bind(Service71::class.java, DefaultService71::class.java)
        .bind(Service72::class.java, DefaultService72::class.java)
        .bind(Service73::class.java, DefaultService73::class.java)
        .bind(Service74::class.java, DefaultService74::class.java)
        .bind(Service75::class.java, DefaultService75::class.java)
        .bind(Service76::class.java, DefaultService76::class.java)
        .bind(Service77::class.java, DefaultService77::class.java)
        .bind(Service78::class.java, DefaultService78::class.java)
        .bind(Service79::class.java, DefaultService79::class.java)
        .bind(Service80::class.java, DefaultService80::class.java)
        .bind(Service81::class.java, DefaultService81::class.java)
        .bind(Service82::class.java, DefaultService82::class.java)
        .bind(Service83::class.java, DefaultService83::class.java)
        .bind(Service84::class.java, DefaultService84::class.java)
        .bind(Service85::class.java, DefaultService85::class.java)
        .bind(Service86::class.java, DefaultService86::class.java)
        .bind(Service87::class.java, DefaultService87::class.java)
        .bind(Service88::class.java, DefaultService88::class.java)
        .bind(Service89::class.java, DefaultService89::class.java)
        .bind(Service90::class.java, DefaultService90::class.java)
        .bind(Service91::class.java, DefaultService91::class.java)
        .bind(Service92::class.java, DefaultService92::class.java)
        .bind(Service93::class.java, DefaultService93::class.java)
        .bind(Service94::class.java, DefaultService94::class.java)
        .bind(Service95::class.java, DefaultService95::class.java)
        .bind(Service96::class.java, DefaultService96::class.java)
        .bind(Service97::class.java, DefaultService97::class.java)
        .bind(Service98::class.java, DefaultService98::class.java)
        .bind(Service99::class.java, DefaultService99::class.java)
        .bind(Service100::class.java, DefaultService100::class.java)
        .bind(Service101::class.java, DefaultService101::class.java)
        .buildAndInit()

    val app = ServiceLocator
        .get(Service::class.java)
    println(app.name())
}