package io.heapy.komodo

import io.heapy.komodo.di.createContextAndGet
import io.heapy.komodo.di.module
import io.heapy.komodo.di.provide
import io.heapy.komodo.di.type
import io.heapy.sample.common2.*

suspend fun main() {
    val s = createContextAndGet(type<Service>(), mainModule)
    println(s.name())
}

val mainModule by module {
    provide<Service>(::DefaultService)
    provide<Service1>(::DefaultService1)
    provide<Service2>(::DefaultService2)
    provide<Service3>(::DefaultService3)
    provide<Service4>(::DefaultService4)
    provide<Service5>(::DefaultService5)
    provide<Service6>(::DefaultService6)
    provide<Service7>(::DefaultService7)
    provide<Service8>(::DefaultService8)
    provide<Service9>(::DefaultService9)
    provide<Service10>(::DefaultService10)
    provide<Service11>(::DefaultService11)
    provide<Service12>(::DefaultService12)
    provide<Service13>(::DefaultService13)
    provide<Service14>(::DefaultService14)
    provide<Service15>(::DefaultService15)
    provide<Service16>(::DefaultService16)
    provide<Service17>(::DefaultService17)
    provide<Service18>(::DefaultService18)
    provide<Service19>(::DefaultService19)
    provide<Service20>(::DefaultService20)
    provide<Service21>(::DefaultService21)
    provide<Service22>(::DefaultService22)
    provide<Service23>(::DefaultService23)
    provide<Service24>(::DefaultService24)
    provide<Service25>(::DefaultService25)
    provide<Service26>(::DefaultService26)
    provide<Service27>(::DefaultService27)
    provide<Service28>(::DefaultService28)
    provide<Service29>(::DefaultService29)
    provide<Service30>(::DefaultService30)
    provide<Service31>(::DefaultService31)
    provide<Service32>(::DefaultService32)
    provide<Service33>(::DefaultService33)
    provide<Service34>(::DefaultService34)
    provide<Service35>(::DefaultService35)
    provide<Service36>(::DefaultService36)
    provide<Service37>(::DefaultService37)
    provide<Service38>(::DefaultService38)
    provide<Service39>(::DefaultService39)
    provide<Service40>(::DefaultService40)
    provide<Service41>(::DefaultService41)
    provide<Service42>(::DefaultService42)
    provide<Service43>(::DefaultService43)
    provide<Service44>(::DefaultService44)
    provide<Service45>(::DefaultService45)
    provide<Service46>(::DefaultService46)
    provide<Service47>(::DefaultService47)
    provide<Service48>(::DefaultService48)
    provide<Service49>(::DefaultService49)
    provide<Service50>(::DefaultService50)
    provide<Service51>(::DefaultService51)
    provide<Service52>(::DefaultService52)
    provide<Service53>(::DefaultService53)
    provide<Service54>(::DefaultService54)
    provide<Service55>(::DefaultService55)
    provide<Service56>(::DefaultService56)
    provide<Service57>(::DefaultService57)
    provide<Service58>(::DefaultService58)
    provide<Service59>(::DefaultService59)
    provide<Service60>(::DefaultService60)
    provide<Service61>(::DefaultService61)
    provide<Service62>(::DefaultService62)
    provide<Service63>(::DefaultService63)
    provide<Service64>(::DefaultService64)
    provide<Service65>(::DefaultService65)
    provide<Service66>(::DefaultService66)
    provide<Service67>(::DefaultService67)
    provide<Service68>(::DefaultService68)
    provide<Service69>(::DefaultService69)
    provide<Service70>(::DefaultService70)
    provide<Service71>(::DefaultService71)
    provide<Service72>(::DefaultService72)
    provide<Service73>(::DefaultService73)
    provide<Service74>(::DefaultService74)
    provide<Service75>(::DefaultService75)
    provide<Service76>(::DefaultService76)
    provide<Service77>(::DefaultService77)
    provide<Service78>(::DefaultService78)
    provide<Service79>(::DefaultService79)
    provide<Service80>(::DefaultService80)
    provide<Service81>(::DefaultService81)
    provide<Service82>(::DefaultService82)
    provide<Service83>(::DefaultService83)
    provide<Service84>(::DefaultService84)
    provide<Service85>(::DefaultService85)
    provide<Service86>(::DefaultService86)
    provide<Service87>(::DefaultService87)
    provide<Service88>(::DefaultService88)
    provide<Service89>(::DefaultService89)
    provide<Service90>(::DefaultService90)
    provide<Service91>(::DefaultService91)
    provide<Service92>(::DefaultService92)
    provide<Service93>(::DefaultService93)
    provide<Service94>(::DefaultService94)
    provide<Service95>(::DefaultService95)
    provide<Service96>(::DefaultService96)
    provide<Service97>(::DefaultService97)
    provide<Service98>(::DefaultService98)
    provide<Service99>(::DefaultService99)
    provide<Service100>(::DefaultService100)
    provide<Service101>(::DefaultService101)
}

